### ISSUE TITLE
Should we maybe check and publish this as a package?

### ISSUE THREAD

**Issue by kellertuer** [dmerkert/IntegerSmithNormalForm.jl#2]
I needed this feature again a while back and it is stimm not in the Julia Registry. We could revive this package a bit and register it maybe?

**Comment by dmerkert** [comment]
We can sure do that. However, my last contact with the Julia language end ecosystem was 5 years ago. So that's nothing  I can do in a hurry.
Maybe you can help.
Seems to have a few bugs a well, at least according to the report by Travis...

**Comment by kellertuer** [comment]
Cool.
I can surely help with that, also to switch the tests to GitHub Actions and such, which is a much nicer system these days.

I hope to find time to do that somewhen then :)

**Comment by dmerkert** [comment]
Great, thanks! Also, we should review the license. Not sure why we/I picked that one. If I didn't miss it, it not even requires a mention of the author(s).

**Comment by kellertuer** [comment]
No Problem I can also update that to the one I usually have with my Julia packages.

**Comment by kellertuer** [comment]
I did most of the rework – I hope – on master

* using GitHub Actions instead of Travis
* using Project.toml instead of REQIRE
* refactor most of the code to Julia 1.0

Still missing:

* An example in the readme of how to use SNF (maybe we rename that?)
* edit: tests are running on Julia > 1.1 (had to remove 1.0 since we now use `isnothing`)

_edit:_ So mainly the naming of the snf function and a Readme might be missing (sorry did all that on master for now, but I hope the project is small enough for that.

**Comment by kellertuer** [comment]
I think there are just a few small points left to do @dmerkert 

1. should we keep the function name `SNF`? We could also take `integer_smith_normalform` or `smith_normalform`, I feel these names
2. We should work on the docs a bit and put one or two examples in the readme
3. Concerning the docs – the PDF link does no longer work, do we maybe have a nice (published/article/wiki?) reference for the algorithm?
4. I added the only mail adress I know of you to the `Project.toml` feel free to update/change that.

After these points and as soon as you then agree, I can take care of the registration;

5. I hope I can add JuliaRegistrator here 
6. I have to check (again) how to setup TagBot.

**Comment by kellertuer** [comment]
* I changed the license to the general MIT License
* since the snf is a function, I renamed the function to `snf` (and `snf!`)
* the transform without the outer once is now called `elementary_divisors` and only returns a vector.
* I added a TagBot Action that automatically tags versions and creates releases
* added an example to the Readme.md

We still should add https://github.com/JuliaRegistries/Registrator.jl but I do not seem to have enough rights. Then this should be good to go. Can you check @dmerkert? Either add it or give me enough rights to do that ;)

The rest should now be set up and ready. Would be great if we could register that this month :)

**Comment by kellertuer** [comment]
@dmerkert did you have time to check? I would like to add this package as a dependency to another package, but that only work well if it is registered. We would still need @JuliaRegistrator added here, for which I do not have enough rights.

**Comment by kellertuer** [comment]
@dmerkert I would really need this package in a new package I am writing. I can offer to fork this and publish it and we move the published version back here once you had time to activate e.g. the JuliaRegistrator bot?

**Comment by kellertuer** [comment]
@dmerkert please answer. I need this package somehow soon.

**Comment by dmerkert** [comment]
@kellertuer Sorry for taking so long! I have quite a lot going on at home at the moment. I have added the Julia Registrator (clicking the install button, yeah :-) ).

**Comment by kellertuer** [comment]
Supert!
Sure, sometimes this thing called life takes over things. I triggered the registration and that worked well.

There is a 3-day waiting period for new packages, after that it should be merged and hopefully TagBot has enough rights to do the rest :)

**Comment by kellertuer** [comment]
The publishing went well and we have a first tagged and released version 👍
